## Basic Configuration

baseurl = "/"  
builddrafts = false
canonifyurls = false
languageCode = "en-US"
paginate = 6

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Rahul Sharma"
title = "creativcoder's blog"

theme = "bleak"

## Hugo Built-in Features
disqusShortname = "creativcoder" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Rahul Sharma"
authorImage = "logo.jpg"
intro = "Curious"
cover = "/poly.png"
dateFormat = "Jan 2, 2006"
Subtitle = "Autodidact code tinkerer. Loves exploring the bleeding edge in tech."
description = "This blog contains my thoughts and ideas about the fascinating world of computer science."

## Site Meta Settings
[params.meta]
description = "Bleak theme"
keywords = "minimalist,flat,bleak,ghost"

## Social Accounts
[params.social]
github = "creativcoder"
linkedIn = "creativcoder"
twitter = "creativcoder"
facebook = "rsconcepts"
google = "creativcoder"
email = "rsconceptx@gmail.com"

## Extras
[params.extra]
copyright = "© 2016. Rahul Sharma. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredBy = true
highlightJS = true

## Main Menu
[[menu.main]]
    name = "Home"
    identifier = "Home"
    weight = 100
    url = "/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "Twitter: creativcoder"
    weight = 300
[[menu.main]]
    name = "Github: creativcoder"
    weight = 400
[[menu.main]]
    name = "IRC creativcoder@irc.mozilla.org"
    weight = 500
