baseurl = "https://creativcoder.github.io/"
languageCode = "en-us"
title = "creativcoder's blog"
theme = "hugo-type-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = "creativcoder"
# Add your tracking code to enable Google Analytics
googleAnalytics = "UA-87920648-1"
# Posts per page
paginate = 10
# Comment the themesDir option if you use this theme in production
# themesDir = "../.."

[params]
	author = "Rahul Sharma"
	description = ""
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = ""
	# Either show custom avatar on the top
	# left by adding the filename in below
	avatar = "img/avatar.jpg"
	# or use Gravatar by adding your email address to generate a unique avatar
	# gravatar = "rsconceptx@gmail.com"

	headerText = "<br><br><br> thoughts.iter().map(|code|) <br><br><br>"
	# To add a header background to the main site, save your image under static/img/.
	# If no image path is provided, a orange background will be shown instead.
	headerImage = "http://i.imgur.com/0u3RQeg.jpg"
	copyright = "Released under the MIT license<br>Powered by [Hugo](//gohugo.io/) with the [Type Theme](//github.com/digitalcraftsman/hugo-type-theme)"


	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = true
		homepage = true
		email = "rsconceptx@gmail.com"
		behance = ""
		bitbucket  =""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "creativcoder"
		linkedin = "creativcoder"
		pinterest = ""
		soundcloud = ""
		stackexchange = "creativcoder"
		steam = ""
		tumblr = ""
		twitter = "creativcoder"
		wordpress = ""
		trello = ""
